### ISSUE TITLE
mcstatus still has the socket closing exception bug

### ISSUE THREAD

**Issue by kevinkjt2000** [kevinkjt2000/bowser#21]
Need to replace mcstatus with my fork to grab the fix dinnerbone/mcstatus#56
Otherwise, this ugliness is logged occasionally when discord.py does a reconnect.
```
bot_1    | Exception ignored in: <bound method TCPSocketConnection.__del__ of <mcstatus.protocol.connection.TCPSocketConnection object at 0x7fe06beef710>>
bot_1    | Traceback (most recent call last):
bot_1    |   File "/usr/local/lib/python3.6/site-packages/mcstatus/protocol/connection.py", line 153, in __del__
bot_1    |     self.socket.close()
bot_1    | AttributeError: 'TCPSocketConnection' object has no attribute 'socket'
bot_1    | Exception ignored in: <bound method TCPSocketConnection.__del__ of <mcstatus.protocol.connection.TCPSocketConnection object at 0x7fe06bde84e0>>
bot_1    | Traceback (most recent call last):
bot_1    |   File "/usr/local/lib/python3.6/site-packages/mcstatus/protocol/connection.py", line 153, in __del__
bot_1    |     self.socket.close()
bot_1    | AttributeError: 'TCPSocketConnection' object has no attribute 'socket'
```

**Comment by kevinkjt2000** [comment]
Resolved by #22
